name: CLA Assistant

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  cla-check:
    runs-on: self-hosted
    steps:
      - name: CLA Assistant
        if: (github.event.comment.body == 'recheck'
          || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA'
          || contains(github.event.comment.body, '@cla-bot check')
          || contains(github.event.comment.body, '@cla-bot recheck')
          ) || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Configure CLA bot settings
        with:
          # Path to the CLA document
          path-to-document: 'https://github.com/I-m-A-g-I-n-E/A-G-I/blob/main/CLA.md'
          # Branch for storing CLA signatures
          branch: 'cla-signatures'
          # Allowlist for users who don't need to sign (bots, etc.)
          allowlist: dependabot[bot],github-actions[bot]
          # CLA signing instructions
          custom-messages: |
            **Welcome to A-G-I!** 
            
            Thank you for your contribution! Before we can merge your pull request, we need you to sign our Contributor License Agreement (CLA).
            
            📋 **Please review our [CLA document](https://github.com/I-m-A-g-I-n-E/A-G-I/blob/main/CLA.md)** which explains:
            - Your rights as a contributor
            - License terms for your contributions  
            - How your contributions will be used
            
            ✍️ **To sign the CLA**, please comment on this PR with:
            ```
            I have read the CLA Document and I hereby sign the CLA
            ```
            
            ❓ **Questions?** See our [CONTRIBUTING.md](https://github.com/I-m-A-g-I-n-E/A-G-I/blob/main/CONTRIBUTING.md) or create an issue with the "CLA" label.
            
            Once you sign the CLA, this check will pass and your contribution can be reviewed for merging.
          # Custom no-CLA message  
          custom-pr-sign-comment: |
            Thank you for signing the CLA! ✅
            
            Your contribution is now ready for review. A maintainer will review your changes and provide feedback.
            
            💡 **Next Steps:**
            - Ensure all tests pass
            - Address any review feedback
            - Keep your PR up to date with the main branch
            
            Thanks for contributing to A-G-I! 🚀
          # Lock the conversation after CLA is signed
          lock-pullrequest-aftermerge: false
          # Use organization-wide CLA if desired
          use-dco-flag: false